# Generated by Django 2.1 on 2019-06-17 06:20

import Watches.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retailer_profile', '0002_auto_20190318_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_id', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Watches.models.upload_image_path)),
                ('category', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=120)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer_profile.Retailer')),
            ],
        ),
    ]
