# Generated by Django 2.1 on 2019-06-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190610_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquet',
            name='retailer',
        ),
        migrations.DeleteModel(
            name='Bouquet',
        ),
    ]
