# Generated by Django 2.1 on 2019-03-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailer',
            old_name='contact',
            new_name='gstno',
        ),
        migrations.RenameField(
            model_name='retailer',
            old_name='gstn',
            new_name='phone',
        ),
    ]
