# Generated by Django 2.1 on 2019-07-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_auto_20190619_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='cake_id',
            field=models.SlugField(default='abc'),
        ),
    ]
